/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFACE2_H_RPCGEN
#define _INTERFACE2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 20

struct notificacion_sensores_fuera_rango {
	int frecuencia_cardiaca;
	int tension_arterial;
	int frecuencia_respiratoria;
	int saturacion_oxigeno;
	int temperatura;
};
typedef struct notificacion_sensores_fuera_rango notificacion_sensores_fuera_rango;

#define enviar_notificacion 0x20000002
#define enviar_notificacion_1 2

#if defined(__STDC__) || defined(__cplusplus)
#define enviarNotificacion 1
extern  bool_t * enviarnotificacion_2(notificacion_sensores_fuera_rango *, CLIENT *);
extern  bool_t * enviarnotificacion_2_svc(notificacion_sensores_fuera_rango *, struct svc_req *);
extern int enviar_notificacion_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define enviarNotificacion 1
extern  bool_t * enviarnotificacion_2();
extern  bool_t * enviarnotificacion_2_svc();
extern int enviar_notificacion_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_notificacion_sensores_fuera_rango (XDR *, notificacion_sensores_fuera_rango*);

#else /* K&R C */
extern bool_t xdr_notificacion_sensores_fuera_rango ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFACE2_H_RPCGEN */
