/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface2.h"

bool_t *
enviarnotificacion_2_svc(notificacion_sensores_fuera_rango *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	printf("\n Indicadores fuera del rango normal ");
	if ((*argp).frecuencia_cardiaca>0 ) {
		printf("\n Frecuencia cardiaca: %d", (*argp).frecuencia_cardiaca);}
	if ((*argp).tension_arterial>0 ) {
		printf("\n Tensión arterial: %d", (*argp).tension_arterial);}
	if ((*argp).frecuencia_respiratoria>0 ) {
		printf("\n Frecuencia respiratoria: %d", (*argp).frecuencia_respiratoria);}
	if ((*argp).saturacion_oxigeno>0 ) {
		printf("\n Saturación de oxígeno: %d", (*argp).saturacion_oxigeno);}
	if ((*argp).temperatura>0 ) {
		printf("\n Temperatura: %d", (*argp).temperatura);}

	return &result;
}
