/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface1.h"
#include "interface2.h"

int determinarRangoNormalFrecuenciaCardiaca(int frecuencia) {
        return frecuencia; //retorna -1 si no está fuera de rango
}

int determinarRangoNormalPresionArterial(int presion) {
        return -1; //retorna -1 si no está fuera de rango
}

int determinarRangoNormalPFrecuenciaRespiratoria(int frecuencia) {
        return frecuencia; //retorna -1 si no está fuera de rango
}

int determinarRangoNormalSaturacionOxigeno(int saturacion) {
        return -1; //retorna -1 si no está fuera de rango
}

int determinarRangoNormalTemperatura(int temperatura) {
        return temperatura; //retorna -1 si no está fuera de rango
}

bool_t *
enviardatossensores_2_svc(nodo_datos_sensores *argp, struct svc_req *rqstp)
{
        static bool_t  result;
	CLIENT *clnt;
	bool_t *result_1;
	notificacion_sensores_fuera_rango objNotificacion;
#ifndef DEBUG
        clnt = clnt_create ("localhost", enviar_notificacion, enviar_notificacion_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror ("localhost");
		exit (1);
	}
#endif /* DEBUG */
        printf("Enviado datos al servidor de notificaciones\n");
        objNotificacion.frecuencia_cardiaca = determinarRangoNormalFrecuenciaCardiaca((*argp).frecuencia_cardiaca);
        objNotificacion.tension_arterial = determinarRangoNormalPresionArterial((*argp).tension_arterial);
        objNotificacion.frecuencia_respiratoria = determinarRangoNormalPFrecuenciaRespiratoria((*argp).frecuencia_respiratoria);
        objNotificacion.saturacion_oxigeno = determinarRangoNormalSaturacionOxigeno((*argp).saturacion_oxigeno);
        objNotificacion.temperatura = determinarRangoNormalTemperatura((*argp).temperatura);
        
        result_1 = enviarnotificacion_2(&objNotificacion, clnt);
        if (result_1 == (bool_t *) NULL) {
          clnt_perror (clnt, "call failed");
        }
#ifndef DEBUG
        clnt_destroy (clnt);
#endif /* DEBUG */

	return &result;
}
