/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface1.h"


void
enviar_datos_sensores_2(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	nodo_datos_sensores  objDatosSensores;

#ifndef	DEBUG
	clnt = clnt_create (host, enviar_datos_sensores, enviar_datos_sensores_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

        printf("\n Digite la frecuencia cardiaca: ");
        scanf("%d", &objDatosSensores.frecuencia_cardiaca);
        
        printf("\n Digite la tensión arterial: ");
        scanf("%d", &objDatosSensores.tension_arterial);
        
        printf("\n Digite la frecuencia respiratoria: ");
        scanf("%d", &objDatosSensores.frecuencia_respiratoria);
        
        printf("\n Digite la saturación oxígeno: ");
        scanf("%d", &objDatosSensores.saturacion_oxigeno);
        
        printf("\n Digite la temperatura: ");
        scanf("%d", &objDatosSensores.temperatura);

	result_1 = enviardatossensores_2(&objDatosSensores, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	enviar_datos_sensores_2 (host);
exit (0);
}
