/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFACE1_H_RPCGEN
#define _INTERFACE1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 20

struct nodo_datos_sensores {
	int frecuencia_cardiaca;
	int tension_arterial;
	int frecuencia_respiratoria;
	int saturacion_oxigeno;
	int temperatura;
};
typedef struct nodo_datos_sensores nodo_datos_sensores;

#define enviar_datos_sensores 0x20000001
#define enviar_datos_sensores_1 2

#if defined(__STDC__) || defined(__cplusplus)
#define enviarDatosSensores 1
extern  bool_t * enviardatossensores_2(nodo_datos_sensores *, CLIENT *);
extern  bool_t * enviardatossensores_2_svc(nodo_datos_sensores *, struct svc_req *);
extern int enviar_datos_sensores_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define enviarDatosSensores 1
extern  bool_t * enviardatossensores_2();
extern  bool_t * enviardatossensores_2_svc();
extern int enviar_datos_sensores_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nodo_datos_sensores (XDR *, nodo_datos_sensores*);

#else /* K&R C */
extern bool_t xdr_nodo_datos_sensores ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFACE1_H_RPCGEN */
